<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us" lang="en-us">
<head>
  <link href="https://gmpg.org/xfn/11" rel="profile">
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="Hugo 0.74.3" />

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>异步 &middot; My New Hugo Site</title>
  <meta name="description" content="" />

  
  <link type="text/css" rel="stylesheet" href="http://zhouzhou829.github.io/css/print.css" media="print">
  <link type="text/css" rel="stylesheet" href="http://zhouzhou829.github.io/css/poole.css">
  <link type="text/css" rel="stylesheet" href="http://zhouzhou829.github.io/css/syntax.css">
  <link type="text/css" rel="stylesheet" href="http://zhouzhou829.github.io/css/hyde.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface|PT+Sans:400,400i,700">


  
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
  <link rel="shortcut icon" href="/favicon.png">

  
  
</head>

  <body class=" ">
  <aside class="sidebar">
  <div class="container sidebar-sticky">
    <div class="sidebar-about">
      <a href="http://zhouzhou829.github.io/"><h1>My New Hugo Site</h1></a>
      <p class="lead">
      An elegant open source and mobile first theme for <a href="http://hugo.spf13.com">hugo</a> made by <a href="http://twitter.com/mdo">@mdo</a>. Originally made for Jekyll.
      </p>
    </div>

    <nav>
      <ul class="sidebar-nav">
        <li><a href="http://zhouzhou829.github.io/">Home</a> </li>
        
      </ul>
    </nav>

    <p>&copy; 2021. All rights reserved. </p>
  </div>
</aside>

    <main class="content container">
    <div class="post">
  <h1>异步</h1>
  <time datetime=2015-10-25T08:36:54-0700 class="post-date">Sun, Oct 25, 2015</time>
  <h1 id="一-event-loop和宏微任务相关知识理解">一 、event loop和宏、微任务相关知识理解</h1>
<ul>
<li>
<p>1 为什么js会是单线程的？</p>
<p>因为js是运行在浏览器的脚本语言，主要操作有dom节点的操作及用户之间的互动，假如js是多线程的，如果用户连续操作dom的增删改那么我们要以那个线程为准呢，为了避免这些问题，所以js在设计之初就定为单线程</p>
</li>
<li>
<p>2 任务队列及event loop 事件循环</p>
<p>由于js单线程的原因，所有任务都要排队等待一个一个执行，如果cpu空闲的情况下依旧等待类似ajax的网络请求结束后在往下执行，js设计者意识到这个问题这时主线程完全可以不管IO设备，挂起处于等待中的任务，先运行排在后面的任务。等到IO设备返回了结果，再回过头，把挂起的任务继续执行下去。
所以分成了异步任务和同步任务，具体整理下任务的运行机制</p>
<p>（1）所有同步任务都在主线程上执行，形成一个执行栈</p>
<p>（2）主线程之外，还存在一个&quot;任务队列&quot;异步的进入Event   Table并注册函数 ，当指定的事情完成时，Event Table会将这个函数移入Event Queue。</p>
<p>（3）一旦&quot;执行栈&quot;中的所有同步任务执行完毕（js引擎存在monitoring process进程，会持续不断的检查主线程执行栈是否为空），系统就会读取&quot;任务队列&rdquo;，看看里面有哪些事件。那些对应的异步任务，于是结束等待状态，进入执行栈，开始执行</p>
<p>（4）主线程不断重复上面的第三步。</p>
</li>
<li>
<p>3 宏任务和微任务</p>
<p>宏任务和微任务均为异步任务，有区别的是他们的执行顺序，Event Loop的走向和取值 每一个宏任务和微任务执行完的之后都判断是否还有微任务，如果有微任务继续执行微任务，没有则开始下一个宏任务，这样的一个循环</p>
<p>我们常见的微任务及宏任务
宏任务：包括整体代码script，setTimeout，setInterval、setImmediate。
微任务：原生Promise(有些实现的promise将then方法放到了宏任务中)、process.nextTick、MutationObserver</p>
</li>
</ul>
<pre><code>Promise.resolve().then(()=&gt;{
  console.log('Promise1') 
  setTimeout(()=&gt;{
    console.log('setTimeout2')。
  },0)
})

setTimeout(()=&gt;{
  console.log('setTimeout1')
  Promise.resolve().then(()=&gt;{
    console.log('Promise2')   
  })
},0)
解析 两个异步任务直接进入任务队列，首先执行微任务 Promise.resolve() //输出Promise1 这一轮的微任务执行完毕那么任务队列会新加一个setTimeout2的异步任务 并继续执行任务对列下一个宏任务第二个setTimeout 会输出setTimeout1，然后在任务队列中加如一个微任务 console.log('Promise2') ，检测到微任务未执行，执行微任务Promise2后，再是下一轮宏任务setTimeout2   

console.log('1');
 setTimeout(function() {
    console.log('2');
    process.nextTick(function() {
        console.log('3');
    })
    new Promise(function(resolve) {
        console.log('4');
        resolve();
    }).then(function() {
        console.log('5')
    })
})
process.nextTick(function() {
    console.log('6');
})
new Promise(function(resolve) {
    console.log('7');
    resolve();
}).then(function() {
    console.log('8')
})

setTimeout(function() {
    console.log('9');
    process.nextTick(function() {
        console.log('10');
    })
    new Promise(function(resolve) {
        console.log('11');
        resolve();
    }).then(function() {
        console.log('12')
    })
})
解析 首先我们先拆分任务并建立任务队列
//第一轮事件循环
console.log(1)  直接输出 1
setTimeout   任务队列加一个宏任务
process.nextTick 任务队列加一个微任务
new Promise 立刻执行 直接输出 7 then会创建一个微任务
setTimeout 任务队列加一个宏任务 执行完以后检查到还有微任务微执行
本轮事件产生的两个微任务执行 输出 6 和8
//第二轮事件循环开始此时任务队列剩余两个宏任务中的第一个setTimeout
 console.log('2') 直接输出2 
 任务队列加一个为微任务 process
 new Promise 立刻执行直接输出4 then创建微任务
 本轮事件产生的两个微任务执行 输出 3 和5
 此时任务对列中没有微任务 开启下一轮宏任务执行顺序跟本轮相同
 此次的输出是 1 7 6 8 2 4 3 5 9 11 10 12 
</code></pre><h1 id="二promise-相关内容">二、promise 相关内容</h1>
<ul>
<li>有三种状态：pending fulfilled和rejected，。</li>
<li>只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。</li>
<li>一旦状态确定了是不可以改变并且能从pending变为fulfilled和从pending变为rejected这两种。</li>
<li>如果状态已经定型，你再对Promise对象添加回调函数，也会立即得到这个结果。</li>
<li>无法取消Promise，一旦新建它就会立即执行，无法中途取消。</li>
<li>如果不设置回调函数，Promise内部抛出的错误，不会反应到外部</li>
<li>当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）</li>
<li>Promise.prototype.then  定义在对象原型上的方法 为 Promise 实例添加状态改变时的回调函数。then方法的第一个参数是resolved状态的回调函数，第二个参数（可选）是rejected状态的回调函数，注意返回的是一个新的promise实例，
在采用链式调用情况下
1.若第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数。
2.若第一个返回的还是一个Promise对象，这时后一个回调函数，就会等待该Promise对象的状态发生变化，才会被调用。</li>
</ul>
<pre><code>const p1 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; reject(new Error('fail')), 3000)
})

const p2 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; resolve(p1), 1000)
})

p2
  .then(result =&gt; console.log(result))
  .catch(error =&gt; console.log(error))
   解析： p2 1秒以后resolve了p1由于p1还是一个promise所以这里的then针对p1 由于p1 3秒以后reject 所以被catch捕获 输入结果为error
</code></pre><p>promise 常用的几种方法总结</p>
<ul>
<li>Promise.all() 接受参数为一个数组，将多个promise实例合并为一个新的Promise，并且数组中的每一个都是一个promise实例，如果不是会自动用Promise.resolve()将其转化，若数组中的每一项的状态都转化为fulfilled  那么会将返回值合并到一个新的数组然后传递到新的Promise，若其中某一项rejected，那么新的Promise 状态也会变为rejected  那么第一个rejected将会回调给新的数据的rejected</li>
</ul>
<pre><code>const p1 = new Promise((resolve, reject) =&gt; {
  resolve('hello');
})
.then(result =&gt; result)
.catch(e =&gt; e);

const p2 = new Promise((resolve, reject) =&gt; {
  throw new Error('报错了');
})
.then(result =&gt; result)
.catch(e =&gt; e);

Promise.all([p1, p2])
.then(result =&gt; console.log(result))
.catch(e =&gt; console.log(e));
解析：首先p1 resolve p2虽然new error 但有自己的catch方法，返回的是一个新的Promise实例，p2指向的实际上是这个实例。该实例执行完catch方法后，也会变成resolved，所以两个都是resolve 进入then方法里面
</code></pre><ul>
<li>Promise.race() 跟all方法一样同样接收数组返回一个新的Promise实例，但是不同的是，如果数组中的某一个实例状态发生变化，那么这个新的Promise状态就会变化</li>
</ul>
<pre><code>const p = Promise.race([
  fetch('/resource-that-may-take-a-while'),
  new Promise(function (resolve, reject) {
    setTimeout(() =&gt; reject(new Error('request timeout')), 5000)
  })
]);

p
.then(console.log)
.catch(console.error);
如果5秒之内fetch请求的没有反应，那么p会直接reject console error 

</code></pre><p>*Promise.allSettled() 接受一个数组返回新的Promise实例，无论数组里的Promise 是fulfilled还是rejected ，一旦结束状态总是fulfilled，结束后返回给回调的数组每一项都是一个对象，并且对象中有status参数，用来标记数组里面的Promise的状态</p>
<p>*Promise.resolve()将普通对象转化为promise对象
1.如果参数是 Promise 实例，那么Promise.resolve将不做任何修改、原封不动地返回这个实例。
2.如果参数是一个thenable对象，那么将转化为Promise并且立即执行
3.如果参数不是对象或者是空那么直接返回一个resolved状态的 Promise 对象。</p>
<pre><code>let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};

let p1 = Promise.resolve(thenable);
p1.then(function(value) {
  console.log(value);  // 42
});
</code></pre><ul>
<li>Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected。</li>
<li>Promise.try()</li>
</ul>
<h1 id="三generator-函数相关内容">三、Generator 函数相关内容</h1>
<p>es6新提出的一个异步的解决方案，语法上可以理解为一个函数的状态机，封装了多个内部状态 形式上Generator是一个普通函数function关键字与函数名之间有一个星号；二是，函数体内部使用yield表达式（函数暂停的一个标志），定义不同的内部状态，与普通函数不一样的是 Generator函数在函数调用的时候 并不会执行 返回的也不是函数执行的结果，而是一个指向内部的指针对象，必须调用遍历器对象的next方法，使得指针移向下一个状态,Generator函数内部可以不用yield表达式，这时就变成了一个单纯的暂缓执行函数，调用一个next开始执行</p>
<pre><code>function * hello(){
    yield hello
    yield hi
    return '你好'
}
hello.next() { value: 'hello', done: false} 
hello.next() { value: 'hi', done: false}
hello.next() { value: '你好', done: true}
hello.next() { value: undefined, done: true}

每调用一次next函数，返回一个有着value和done两个属性的对象。value属性表示当前的内部状态的值，是yield表达式后面那个表达式的值；done属性是一个布尔值，表示是否遍历结束。，内部指针就从函数头部或上一次停下来的地方开始执行，直到遇见下一个yield 或者是return 如果没有value 返回undefined
我们看下这个例子

 function* foo(x) {
  var y = yield (x + 1);
  var z = yield (y / 3);
  return (x + y + z);
}
 
var a = foo(5);
a.next()  {value:6, done:false}
a.next() {value:NaN, done:false}
a.next() {value:NaN, done:true}
*由于next方法的参数表示上一个yield表达式的返回值，第一个next方法用来启动遍历器对象，所以不用带有参数。
第一个next 是函数调用的时候传的5 所以计算的时候是 5+1
第二个没有参数 y undefined/3 NAN
第三个没有参数 5+ undefined + NAN 
</code></pre><p>for&hellip;of循环可以自动遍历 Generator 函数运行时生成的Iterator对象，且此时不再需要调用next方法。</p>
<pre><code>function* foo() {
  yield 1;
  yield 2;
  yield 3;
  yield 4;
  yield 5;
  return 6;
}

for (let v of foo()) {
  console.log(v);
}
//12345
注意一旦对象中的done 为true的话 循环终止 所以输出不会有6 
</code></pre><p>除了for&hellip;of循环以外，扩展运算符（&hellip;）、解构赋值和Array.from方法内部调用的，都是遍历器接口。这意味着，它们都可以将 Generator 函数返回的 Iterator 对象，作为参数。</p>
<pre><code>function* numbers () {
  yield 1
  yield 2
  return 3
  yield 4
}

// 扩展运算符
[...numbers()] // [1, 2]

// Array.from 方法
Array.from(numbers()) // [1, 2]

// 解构赋值
let [x, y] = numbers();
x // 1
y // 2

// for...of 循环
for (let n of numbers()) {
  console.log(n)
}
// 1
// 2
</code></pre><h2 id="generatorprototypethrow">Generator.prototype.throw()</h2>
<p>在函数外面抛出错误函数内部捕获错误(前提是Generator必须已经执行了next方法 否则也会报错 )，该方法接受一个参数，然后在函数内部被catch捕获
相关的几点总结</p>
<ul>
<li>
<p>1 一旦抛出错误被Generator内部 捕获了，那么再次抛出错误的时候不会再被Generator捕获，只能被外部捕获，如果抛出的错误，内部函数没有进行try catch捕获 那么直接被外部函数捕获，如果内外都没有捕获，那么程序报错中断</p>
</li>
<li>
<p>2 throw方法被捕获以后，会附带执行一次next方法。</p>
</li>
<li>
<p>3  一旦抛出错误被Generator内部没有捕获，那么就不会在执行下去，再次调用next方法 {value:undefined,done:true}</p>
</li>
<li></li>
</ul>
<h2 id="generatorprototypereturn">Generator.prototype.return()</h2>
<pre><code>return方法，可以返回给定的值，并且终结遍历 Generator 函数，函数内部有try...finally代码块，且正在执行try代码块，那么return方法会导致立刻进入finally代码块，执行完以后，整个函数才会结束。
</code></pre>
<pre><code>function* numbers () {
  yield 1;
  try {
    yield 2;
    yield 3;
  } finally {
    yield 4;
    yield 5;
  }
  yield 6;
}
var g = numbers();
g.next() // { value: 1, done: false }
g.next() // { value: 2, done: false }
g.return(7) // { value: 4, done: false }
g.next() // { value: 5, done: false }
g.next() // { value: 7, done: true }
</code></pre><ul>
<li>next()是将yield表达式替换成一个值。</li>
<li>nthrow()是将yield表达式替换成一个throw语句。</li>
<li>return()是将yield表达式替换成一个return语句。</li>
</ul>
<h1 id="四async-相关内容">四、async 相关内容</h1>
<p>async  函数返回一个 Promise 对象，可以使用then方法添加回调函数。当函数执行的时候，一旦遇到await就会先返回，等到异步操作完成，再接着执行函数体内后面的语句。</p>
<p>几点相关个总结</p>
<ul>
<li>async函数内部return语句返回的值，会成为then方法回调函数的参数。</li>
</ul>
<pre><code> async function f() {
  return 'hello world';
}

f().then(v =&gt; console.log(v))
// &quot;hello world&quot;
</code></pre><ul>
<li>async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。</li>
<li>await命令后面的Promise对象，运行结果可能是rejected，所以最好把await命令放在try&hellip;catch代码块中。</li>
<li>async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误。也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数。</li>
</ul>
<h1 id="五总结js整个发展史中对异步的处理办法有哪些">五、总结js整个发展史中对异步的处理办法有哪些</h1>
<ul>
<li>事件回调 可读性差容易形成回调地狱</li>
</ul>
<pre><code>$.ajax({
    url: &quot;xxxx&quot;,
    success: function (res) {
        $.ajax({
            url: &quot;xxxx&quot;,
            success: function (res1) {
            }
        })
    }
})
</code></pre><ul>
<li>发布订阅  每次请求订阅事件，得到数据后，发布事件如果请求api很多，要订阅很多事件代码冗余，不方便维护</li>
<li>Promise   链式调用，代码易读 但是会有很多then方法罗列</li>
</ul>
<pre><code>var readFile = require('fs-readfile-promise');

readFile(file1)
.then(function (data) {
  console.log(data.toString());
})
.then(function () {
  return readFile(file2);
})

</code></pre><ul>
<li>Generator 调用一次next就会继续向下执行 函数()并没有调用，需要执行一次next</li>
</ul>
<pre><code>function* read() {
    console.log(1);
    let a = yield '123';
    console.log(a);
}
let it = read();
console.log(it.next('1')); // {value:'123',done:false}
console.log(it.next('2')); // {value:undefined,done:true}
</code></pre><ul>
<li>async  Generator的语法糖，比Generator易读、容易理解 代码同步写，同步执行</li>
<li></li>
</ul>
<pre><code>async function readfile(){
    try{
        let data = await fetch('xxxx')
        let data2 = await fetch(''xxxx')
        return data2;
    }catch(e){ 
        console.log('err',e)
    }
}
</code></pre><h1 id="六手写一个promise">六、手写一个Promise</h1>
<pre><code>(function(window){
  const PENGDING = 'pending'
  const RESOLVED = 'resolved'
  const REJECTED = 'rejected'
function Promise(executor){
    const self = this
    self.status = PENGDING
    self.data=''
    self.callbacks = []
    resolve(value){
        if(this.status!==PENGDING) {
            return 
        }
        self.status = RESOLVED
        self.data = value
        if(self.callbacks.length){
            self.callbacks.forEach(item=&gt;{
                setTimeout(()=&gt;{
                    item.onResolved(value)
                })
            })
        }
       
    }
    reject(reason){
        if(this.status!==PENGDING) {
            return 
        }
        self.status = RESOLVED
        self.data = reason
        if(self.callbacks.length){
            self.callbacks.forEach(item=&gt;{
                setTimeout(()=&gt;{
                    item.onRejected(reason)
                })
            })
        }
    }
        try {
            executor(resolve,reject)
        }catch(error){
            reject(error)
        }
   }
   Promise.prototype.then=function(onResolved,onRejected){
       onResolved = typeof onResolved==='function'?onResolved:value=&gt;value 
       onRejected = typeof onRejected==='function'?onRejected:reason=&gt;{ throw reason}
       const self = this
       function handle(callback){
        try{
            const result = callback(self.data)
            if(result instanceof Promise){
              result.then(
              value=&gt;{
              resolve(value) //result成功时让return的promise也成功
              },
              reason=&gt;{reject(reason)}//result失败时让return的promise也失败
              )
            }else{
              // 如果回调不是promise return 的promise就成功 value就是返回值
              resolve(result)
            }
        }catch(error){
        // 如果抛出异常，return的promise 就会失败 reason就是error
            reject(error)
        }
       }
       return new Promise((resolve,reject)=&gt;{
           if(self.status===PENGDING){
               self.callbacks.push({
                   onResolved:  handle(onResolved)
                   onRejected:  handle(onRejected)
               })
           }else if(self.status===RESOLVED){
                setTimeout(()=&gt;{
                  handle(onResolved)
                })
           }else{
                setTimeout(()=&gt;{
                  handle(onRejected)
                })
           }
       })
       
   }
    Promise.prototype.catch=function(onRejected){
        return this.then(undefined,onRejected)
    })
    
window.Promise = Promise
}(window))
</code></pre>
</div>


    </main>

    
      
    
  </body>
</html>
